# Arrakis Infrastructure Blueprint - Render.com
# Minimal configuration - Single database + Single web service

# Database Definitions
databases:
  # Production Database - Smallest paid tier
  - name: arrakis-prod-db
    plan: basic-256mb
    postgresMajorVersion: "17"
    databaseName: arrakis_production
    user: arrakis_prod_user
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Production access"

# Service Definitions
services:
  # Production Web Service - Minimal Hello World
  - type: web
    name: arrakis-prod
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/happydotemdr/arrakis.git
    branch: master
    autoDeploy: false  # Manual deployments for production safety
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /health

    envVars:
      # Database connection
      - key: DATABASE_URL
        fromDatabase:
          name: arrakis-prod-db
          property: connectionString

