# Arrakis Infrastructure Blueprint - Render.com
# Next.js 15 application with PostgreSQL database

# Database Definitions
databases:
  # Production Database
  - name: arrakis-prod-db
    plan: basic-256mb
    postgresMajorVersion: "17"
    databaseName: arrakis_production
    user: arrakis_prod_user
    ipAllowList:
      # Your local machine for Claude Code conversation capture
      - source: 23.113.176.139/32
        description: "Local development - Claude Code hooks"

      # Render internal network for web service access
      - source: 0.0.0.0/0
        description: "Render web service access (temporary - restrict after testing)"

# Service Definitions
services:
  # Next.js Web Service
  - type: web
    name: arrakis-prod
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/happydotemdr/arrakis.git
    branch: master
    autoDeploy: true  # Auto-deploy on push to master
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /

    # Performance optimizations
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 70
      targetMemoryPercent: 80

    # Static asset caching
    headers:
      - path: /_next/static/*
        name: Cache-Control
        value: "public, max-age=31536000, immutable"
      - path: /api/*
        name: Cache-Control
        value: "public, max-age=300, s-maxage=300"

    envVars:
      # Database connection
      - key: DATABASE_URL
        fromDatabase:
          name: arrakis-prod-db
          property: connectionString

      # Direct database URL for Prisma migrations
      - key: DIRECT_URL
        fromDatabase:
          name: arrakis-prod-db
          property: connectionString

      # Next.js configuration
      - key: NODE_ENV
        value: production

      # Node.js optimization flags for better performance on limited resources
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512 --optimize-for-size"

      # NextAuth configuration (for future auth features)
      - key: NEXTAUTH_SECRET
        generateValue: true

      - key: NEXTAUTH_URL
        value: https://arrakis-prod.onrender.com

      # Claude Hook API Key for authentication
      # SECURITY: Set this manually in Render dashboard, not in code
      # Generate with: node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
      - key: CLAUDE_HOOK_API_KEY
        sync: false  # Must be set manually in Render dashboard

